more more files

diff --git a/.config/bin/grimshot b/.config/bin/grimshot
--- a/.config/bin/grimshot
+++ b/.config/bin/grimshot
@@ -6,48 +6,26 @@
 ##  - `slurp`: to select an area
 ##  - `swaymsg`: to read properties of current window
 ##  - `wl-copy`: clipboard utility
-##  - `jq`: json utility to parse swaymsg output
+##  - `jq`: json uliity to parse swaymsg output
 ##  - `notify-send`: to show notifications
+##  - `mktemp`: to create a temporary file
 ## Those are needed to be installed, if unsure, run `grimshot check`
 ##
-## See `man 1 grimshot` or `grimshot usage` for further details.
-
-getTargetDirectory() {
-  test -f ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs && \
-    . ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs
-
-  echo ${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME}}
-}
-
-if [ "$1" = "--notify" ]; then
-  NOTIFY=yes
-  shift 1
-else
-  NOTIFY=no
-fi
+## Examples:
+## `grimshot copy win` - to copy current window
+## `grimshot save area` - to select area and save it to default file (Pictures/Grimshot-$datetime.png)
+## `grimshot save screen ~/screenshot.png` - to save screenshot under ~/screenshot.png
+## `grimshot` - usage
+## `grimshot check` - verify if tools are installed
 
 ACTION=${1:-usage}
 SUBJECT=${2:-screen}
-FILE=${3:-$(getTargetDirectory)/$(date -Ins).png}
-
-if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "check" ]; then
+FILE=${3:-$(xdg-user-dir)/$(date +'Grimshot %Y-%m-%d %H-%M-%S.png')}
+if [ "$ACTION" = "usage" ] ; then
   echo "Usage:"
-  echo "  grimshot [--notify] (copy|save) [active|screen|output|area|window] [FILE|-]"
+  echo "  grimshot copy|save win|screen|area [FILE]"
+  echo "Troubleshoot:"
   echo "  grimshot check"
-  echo "  grimshot usage"
-  echo ""
-  echo "Commands:"
-  echo "  copy: Copy the screenshot data into the clipboard."
-  echo "  save: Save the screenshot to a regular file or '-' to pipe to STDOUT."
-  echo "  check: Verify if required tools are installed and exit."
-  echo "  usage: Show this message and exit."
-  echo ""
-  echo "Targets:"
-  echo "  active: Currently active window."
-  echo "  screen: All visible outputs."
-  echo "  output: Currently active output."
-  echo "  area: Manually select a region."
-  echo "  window: Manually select a window."
   exit
 fi
 
@@ -55,20 +33,14 @@ notify() {
   notify-send -t 3000 -a grimshot "$@"
 }
 notifyOk() {
-  [ "$NOTIFY" = "no" ] && return
-
   TITLE=${2:-"Screenshot"}
   MESSAGE=${1:-"OK"}
   notify "$TITLE" "$MESSAGE"
 }
 notifyError() {
-  if [ $NOTIFY = "yes" ]; then
-    TITLE=${2:-"Screenshot"}
-    MESSAGE=${1:-"Error taking screenshot with grim"}
-    notify -u critical "$TITLE" "$MESSAGE"
-  else
-    echo $1
-  fi
+  TITLE=${2:-"Screenshot"}
+  MESSAGE=${1:-"Error taking screenshot with grim"}
+  notify -u critical "$TITLE" "$MESSAGE"
 }
 
 die() {
@@ -79,7 +51,8 @@ die() {
 
 check() {
   COMMAND=$1
-  if command -v "$COMMAND" > /dev/null 2>&1; then
+  command -v "$COMMAND" > /dev/null 2>&1
+  if [ $? ]; then
     RESULT="OK"
   else
     RESULT="NOT FOUND"
@@ -90,10 +63,7 @@ check() {
 takeScreenshot() {
   FILE=$1
   GEOM=$2
-  OUTPUT=$3
-  if [ ! -z "$OUTPUT" ]; then
-    grim -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
-  elif [ -z "$GEOM" ]; then
+  if [ -z "$GEOM" ]; then
     grim "$FILE" || die "Unable to invoke grim"
   else
     grim -g "$GEOM" "$FILE" || die "Unable to invoke grim"
@@ -108,15 +78,12 @@ if [ "$ACTION" = "check" ] ; then
   check wl-copy
   check jq
   check notify-send
+  check mktemp
   exit
 elif [ "$SUBJECT" = "area" ] ; then
   GEOM=$(slurp -d)
-  # Check if user exited slurp without selecting the area
-  if [ -z "$GEOM" ]; then
-    exit 1
-  fi
   WHAT="Area"
-elif [ "$SUBJECT" = "active" ] ; then
+elif [ "$SUBJECT" = "win" ] ; then
   FOCUSED=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?, .floating_nodes[]?) | select(.focused)')
   GEOM=$(echo "$FOCUSED" | jq -r '.rect | "\(.x),\(.y) \(.width)x\(.height)"')
   APP_ID=$(echo "$FOCUSED" | jq -r '.app_id')
@@ -124,30 +91,22 @@ elif [ "$SUBJECT" = "active" ] ; then
 elif [ "$SUBJECT" = "screen" ] ; then
   GEOM=""
   WHAT="Screen"
-elif [ "$SUBJECT" = "output" ] ; then
-  GEOM=""
-  OUTPUT=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')
-  WHAT="$OUTPUT"
-elif [ "$SUBJECT" = "window" ] ; then
-  GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)
-  # Check if user exited slurp without selecting the area
-  if [ -z "$GEOM" ]; then
-   exit 1
-  fi
-  WHAT="Window"
 else
   die "Unknown subject to take a screen shot from" "$SUBJECT"
 fi
 
 if [ "$ACTION" = "copy" ] ; then
-  takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
+  TMP=$(mktemp) || die "Unable to create temp file: is mktemp installed?"
+  takeScreenshot "$TMP" "$GEOM"
+  wl-copy --type image/png < "$TMP"  || die "Clipboard error"
+  rm "$TMP"
   notifyOk "$WHAT copied to buffer"
 else
-  if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
+  takeScreenshot "$FILE" "$GEOM"
+  if [ $? ]; then
     TITLE="Screenshot of $SUBJECT"
     MESSAGE=$(basename "$FILE")
     notifyOk "$MESSAGE" "$TITLE"
-    echo $FILE
   else
     notifyError "Error taking screenshot with grim"
   fi
